In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# distance =[10,15,17,26]
# time = [0.30,0.47,0.55,1.20]
# speed = distance /time

In [6]:
import numpy as np

# np_distance = np.array(distance)
# np_speed = np.array(time)

# speed = np_distance/np_speed
# speed

In [7]:
np_city = np.array(['LA','NYC','Miami','Huston'])
type(np_city)


numpy.ndarray

In [8]:
city_with_state = np.array([['LA','NYC','Miami','Huston'],['NY', 'CA', 'FL', 'TX']])
type(city_with_state)

numpy.ndarray

In [9]:
city_with_state.ndim

2

In [10]:
np_city.shape

(4,)

In [11]:
np_city.size

4

In [12]:
city_with_state.shape

(2, 4)

In [13]:
city_with_state.size

8

In [14]:
np_city.dtype

dtype('<U6')

In [15]:
np1 = np.array([[1,2,3],[4,5,6]])
np1.dtype

dtype('int32')

In [16]:
np2 = np.array([[1.1,1.2,1.3],[2.1,2.2,2.3]])
np2.dtype

dtype('float64')

In [17]:
np_arr1 = np.array([10,20,30,40])
np_arr2 = np.array([50,60,70,80])
np_arr1+np_arr2

array([ 60,  80, 100, 120])

In [18]:
np_arr3 = np.array([[10,20,30,40],[50,60,70,80]])
np_arr3[0][0]

10

In [19]:
a = np.array([[10,20,30,40],[50,60,70,80]])

In [20]:
a[0,0]

10

In [21]:
a[0:,0:2]

array([[10, 20],
       [50, 60]])

In [22]:
a[0:,-1]

array([40, 80])

In [23]:
b = np.array([[34,56,78,93],[56,73,91,54]])
pass_score = b>60
pass_score

array([[False, False,  True,  True],
       [False,  True,  True, False]])

In [25]:
b[pass_score]

array([78, 93, 73, 91])

In [26]:
from numpy import pi


In [28]:
sqrt = np.sqrt([2,4,8,9])
sqrt

array([1.41421356, 2.        , 2.82842712, 3.        ])

In [30]:
cos_0 = np.cos(0)
cos_0

1.0

In [32]:
cos_pi = np.cos(pi)
cos_pi

-1.0

In [33]:
np.sin(pi/2)

1.0

In [34]:
np.floor([1.2,3.5,4.7,4.1])

array([1., 3., 4., 4.])

In [35]:
np.exp([1,2,3,4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [36]:
a.ravel()

array([10, 20, 30, 40, 50, 60, 70, 80])

In [37]:
a.reshape(4,2)

array([[10, 20],
       [30, 40],
       [50, 60],
       [70, 80]])

In [41]:
a.resize(4,2)

In [43]:
a = a.ravel()

In [44]:
np.hsplit(a,2)

[array([10, 20, 30, 40]), array([50, 60, 70, 80])]

In [48]:
arr_1 = [1,2,3,4]
arr_2 = [5,6,7,8]
arr_3 = np.hstack((arr_1,arr_2))
arr_3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
d = np.array([3,4,5,6])
e = 2
d*e

array([ 6,  8, 10, 12])

In [50]:
f = np.array([2,3])
d*f

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [51]:
# Python program to demonstrate
# array creation techniques
import numpy as np
 
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [52]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [53]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [54]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
            "Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [55]:
# Create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)


A random array:
 [[0.91696839 0.08715552]
 [0.57138066 0.544843  ]]


In [56]:
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [57]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("\nA sequential array with 10 values between"
                                        "0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [58]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)
 
print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)
 
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
